let places: string[]=['Karachi','lahore','Islamabad','Peshawar','Multan'];
console.log("Original order:",places);
console.log('Alphabetical order :',[...places].sort());
console.log("Original order:", places);
places.reverse();
console.log("original order :", places);
places.sort();
console.log("Aphabetical order:",places);
places.reverse();
console.log("Reverse Alphabetical order:",places);
